name:                infinity-class
version:             0.0.0
github:              "AliceRixte/infinity-class"
license:             BSD3
author:              "Alice Rixte"
maintainer:          "alice.rixte@u-bordeaux.fr"
copyright:           "BSD3"

extra-source-files:
- README.md
- CHANGELOG.md

synopsis:            A typeclass for types that can represent infinity.
category:            numeric
description:         Please see the README on GitHub at <https://github.com/AliceRixte/infinity-class/blob/main/README.md>

dependencies:
- base >= 4.19 && < 5

ghc-options:
  - -Wall

tested-with: GHC == 9.8.4

library:
  ghc-options:
  - -O2
  source-dirs: src

